version: '3.2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      dockerfile: Dockerfile
      args:
        ES_VERSION: $ES_VERSION
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge