version: '3.2'
services:
  elasticsearch:
    image: docker.pkg.github.com/techial1042/elastic-star-action/es:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
