name: Build elasticsearch

on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          docker login docker.pkg.github.com --username=${{ secrets.USERNAME }} --password=${{ secrets.TOKEN }}
          chmod +x ./build.sh && ./build.sh
          docker login ${{ secrets.ALIYUN_URL }} --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_TOKEN }}
          docker tag elastic-star-action_elasticsearch:latest ${{ secrets.ALIYUN_IMAGE }}
          docker push ${{ secrets.ALIYUN_IMAGE }}



